### ISSUE TITLE
problem with registering existingInstance after updating to 7.0.0

### ISSUE THREAD

**Issue by SingingBush** [mbierlee/poodinis#12]
I've updated to the latest Poodinis version and found everything ok except this one thing:

```D
SessionFactoryImpl sessionFactory = methodThatCreatesSessionFactory();
        container.register!(SessionFactory, SessionFactoryImpl)(RegistrationOption.doNotAddConcreteTypeRegistration).existingInstance(sessionFactory);
```

The compiler errors with:

```bash
../../../.dub/packages/poodinis-7.0.0/poodinis/source/poodinis/factory.d-mixin-131(133,69): Error: undefined identifier 'EntityMetaData'
../../../.dub/packages/poodinis-7.0.0/poodinis/source/poodinis/factory.d-mixin-131(133,102): Error: undefined identifier 'Dialect'
../../../.dub/packages/poodinis-7.0.0/poodinis/source/poodinis/factory.d-mixin-131(133,128): Error: undefined identifier 'DataSource'
../../../.dub/packages/poodinis-7.0.0/poodinis/source/poodinis/container.d(150,30): Error: template instance poodinis.factory.ConstructorInjectingInstanceFactory!(SessionFactoryImpl) error instantiating
source/config/context.d(28,18):        instantiated from here: register!(SessionFactory, SessionFactoryImpl)
```

the _EntityMetaData_, _Dialect_, and _DataSource_ objects are all from Hibernated and are used to create my SessionFactory instance. Once that has been done I have no need to use them anymore so don't want to add them to the container.

**Comment by mbierlee** [comment]
Does SessionFactoryImpl have any constructors? If so could you show them?

**Comment by SingingBush** [comment]
it's constructor takes the 3 objects I've mentioned but I am already passing them in when I create the object myself:

```D
SessionFactoryImpl factory = new SessionFactoryImpl(metaData, dialect, dataSource);
```

**Comment by mbierlee** [comment]
Release 7.0.1 should solve this issue. Could you verify?

**Comment by SingingBush** [comment]
That certainly did. I committed [c76ecc3](https://github.com/SingingBush/eloquent/commit/c76ecc3c7508b884b26c63b6c41a53ae5fee8da4) to my project to update to poodinis 7.0.1. 

Thanks for the quick response.
